name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/freshdocs-*-darwin-amd64.tar.gz
            dist/freshdocs-*-darwin-arm64.tar.gz
            dist/freshdocs-*-linux-amd64.tar.gz
            dist/freshdocs-*-linux-arm64.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 